sudo: false
language: bash
os:
  - linux

addons:
  apt:
    packages:
      - gperf
      - python
      - python-serial

before_install:
  # Save path to the git respository
  - PROJECT_PATH=$(pwd)

deploy:
  provider: releases
  api_key: bc1b9dc4cda5708841862fc86f4b694eb5f0bbeb
  file: home/travis/build/cgawron/espmqtt/examples/mqtt_tcp/build/mqtt_tcp.bin
  skip_cleanup: true
  on:
    tags: true

install:
  # Install ESP32 toochain following steps as desribed
  # in http://esp-idf.readthedocs.io/en/latest/linux-setup.html
  #
  # Get required packages - already done above, see addons: apt: packages:
  # - sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial
  # Prepare directory for the toolchain
  - mkdir -p ~/esp
  - cd ~/esp
  # Download binary toolchain for the ESP32
  - wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  - tar -xzf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  # Make xtensa-esp32-elf available for all terminal sessions
  - export PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin
  # Get ESP-IDF from github
  - git clone --recursive https://github.com/espressif/esp-idf.git
  # Set the path to ESP-IDF directory
  - export IDF_PATH=~/esp/esp-idf
  # Install python requirements
  - python -m pip install --user -r /home/travis/esp/esp-idf/requirements.txt

script:
  # Go back to the git repository
  - cd $PROJECT_PATH/examples/mqtt_tcp
  # Update configuration so that kconfig doesn't start interactive mode
  - make defconfig
  # Build project from the git repository
  - make -j4
  - cd $PROJECT_PATH/examples/mqtt_ssl
  - make defconfig
  - make -j4
  - cd $PROJECT_PATH/examples/mqtt_ws
  - make defconfig
  - make -j4
  - cd $PROJECT_PATH/examples/mqtt_wss
  - make defconfig
  - make -j4
  - cd $PROJECT_PATH/examples/emitter-client
  - make defconfig
  - make -j4
